### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by ghost** [enanomapper/data.enanomapper.net#10]
I am not sure if CSV export is officially supported, but as it is in the GUI I will report my observations here. They apply to CSV exports from https://apps.ideaconsult.net/enanomapper/bundle as well as to direct downloads from the dataset URI.

I have downloaded all bundles and their structure and content is quite different.

The Marina dataset has only 6 entries, but each entry has a lot of TNF and cell viability values. There is no eNM characterisation. Compound URIs lead to "No records matching the filter.", probably because of the "-1" ID.

In the Nanowiki dataset each row seems to represent a unique nanomaterial (URIs are defunct as in Marina), but only PARTICLE SIZE properties are reported.

The Protein corona dataset has the most details and at a first glance the format/content matches my CSV expectations. Looking closer I can see that in most columns numeric values are prepended with "mean". I would suggest to move that information into the header in order to keep the columns numerical. I still have to check the content and compare with other representation, but for me that would be the preferred CSV representation.

**Comment by vedina** [comment]
Correct, there is no characterisation data in MARINA, and there are replicates and dose response.

The CSV are not the best format for exporting in principle , but due to its popularity we are working on several exporting options including Excel and CSV.

The CSV export for `bundle/id/dataset` is broken as it considers columns from the first entry, and for sparse data this results in missing the rest of the column. This is what happens with NanoWiki .

Will check the compound URI - but the CSV does not export composition and compound URI, see the JSON for such info. This might change in next versions.

The protein corona dataset is very rare example of data that is not sparse. We usually don't have such luxury with other data.

**Comment by ghost** [comment]
> Will check the compound URI

The first column (URI) has entries that point to https://apps.ideaconsult.net/enanomapper/compound/-1 for every substance(compound?).

**Comment by ghost** [comment]
Sorry, I have been confusing the MARINA dataset with Puzyns MODENA dataset, that has much more substances (applies also to #11). Are there any plans to include the MODENA dataset? The spreadsheet looks quite straightforward.

**Comment by vedina** [comment]
Yes, we have tested MODENA spreadsheet in a local instance, will be included in the public version as soon as a permission is obtained.

**Comment by ghost** [comment]
MODENA data is already there, that was quick!

**Comment by vedina** [comment]
Improved the UI for download links, offering exports for different components of a bundle and more formats. 

https://apps.ideaconsult.net/enanomapper/bundle

![image](https://cloud.githubusercontent.com/assets/211190/13721836/aac4c970-e83b-11e5-8861-ad1601c66298.png)

Closing this issue, please open specific tickets per format and component.
