### ISSUE TITLE
Property URIs

### ISSUE THREAD

**Issue by ghost** [enanomapper/data.enanomapper.net#12]
I think I have managed to import public eNM data into my system, and identified data suitable for read-across and QSAR modelling (which is (surprise ;-)) basically the protein corona dataset.

  Total imported: 464
  With nanoparticle characterisation: 394
  With TOX data: 167
  With TOX data and particle characterisation: 160

  TOX Endpoints: 49
  TOX Endpoints with more than one measurement value: 30
  TOX Endpoints with more than 10 nanoparticle measurements: 10

Now I would like to find out more about the selected properties, e.g.

whats the exact difference between the ZETA POTENTIALs

https://apps.ideaconsult.net/enanomapper/property/P-CHEM/ZETA_POTENTIAL_SECTION/ZETA+POTENTIAL/7F8B3FB82019B1CCF8A8C3FD2B5A2DACBDDDB832/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a and
https://apps.ideaconsult.net/enanomapper/property/P-CHEM/ZETA_POTENTIAL_SECTION/ZETA+POTENTIAL/AD2880DCCB16852FB869B7E10223708801EB1B02/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a

which parameter has been log2 transformed for

https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/Log2+transformed/94D664CFE4929A0F400A5AD8CA733B52E049A688/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a

is Total surface area (SAtot) [cm^2] really a toxicity endpoint or a particle characterisation

https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/Total+surface+area+%28SAtot%29/8778865D1C682E0B8EBBEEC2AD2C6EF3D576C858/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a

However if I resolve the property URIs I get little information apart from names and maybe units and some URIs return a 404 error, e.g.

https://apps.ideaconsult.net/enanomapper/property/P-CHEM/PC_GRANULOMETRY_SECTION/SA/NP/2E757CE81FE8CBFBE30226CE6632BCAE1374D648/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a
https://apps.ideaconsult.net/enanomapper/property/P-CHEM/PC_GRANULOMETRY_SECTION/Mol/NP/F9215F417F7AF3E303D6AF553AD6D74973E04971/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a

How would I proceed in such a case to obtain the full feature description, or is it not yet in the system?

**Comment by vedina** [comment]
The Property URIs are dynamics, they are generated from the study json and may not contain all the information. And may not be all resolvable.  The primary format is the study json, rather than the dataset json.

If some phys chem characterisation appears as tox endpoint, this mean the relevant experiment was not correctly annotated  (i.e. the URLs are generated from this annotation and other study info). The annotation should be in the input file and it probably was not there. Will try to fix this in the next DB release. Explanation / documentation on properties will be added, there were previous discussions on the list, but it is indeed not properly documented.

The dataset json actually includes the features metadata, did you consider it ? 

There one can find that the two zeta potential features differ in that one is measured in human serum, and the other is not.

**Comment by ghost** [comment]
> The dataset json actually includes the features metadata, did you consider it ?
> 
> There one can find that the two zeta potential features differ in that one is measured in human serum, and the other is not.

Thanks! I can find it in the dataset json as  feature "annotation" If I try to get the property json representation directly from the URI the annotation is missing (as in the HTML representation).

Whats the meaning of "p" and "o" in the annotations, something like "predicate" and "object"?

**Comment by vedina** [comment]
Yes, exactly, predicate and object.  There are such annotations in OpenTox feature RDF as well . It's an attempt to use the information on experimental conditions.

Yes, the property URIs are not really resolvable, they do not exist as separate objects, but are generated form the study metadata.
