### ISSUE TITLE
search by ontology term

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#34]
It would be really nice to be able to search using an ontology term label or URI.

**Comment by vedina** [comment]
search by ontology label should be possible in the [search applciation](already) , as all the ontology labels are in the synonyms list and considered as phrase.

**Comment by egonw** [comment]
What about adding the URIs as synonyms too then? And the local parts, like BAO_000xxx

Of course, for this to work, you would need to also add the labels and URIs of the superclasses... or is it already doing that?

**Comment by vedina** [comment]
The local parts are already added in the synonym list. Looks like

```
NPO_1374,superparamagnetic_iron_oxide_nanoparticle,SPIO_nanoparticle,SPIO,superparamagnetic_iron_oxide
ENM_9000005,aluminium_oxide_nanoparticle,aluminium_oxide,AlO,Al2O3
ENM_9000006,cerium_oxide_nanoparticle,cerium_oxide,Ce2O3,CeO2
NPO_1486,titanium_oxide_nanoparticle,TiO2_nanoparticle,titanium_oxide,TiO2
NPO_1542,zinc_oxide_nanoparticle,ZnO_nanoparticle,zinc_oxide,ZnO
NPO_1544,copper_oxide_nanoparticle,copper_oxide
NPO_729,iron_oxide_nanoparticle,iron_oxide
```

The parent classes are also in, but may be not in the optimal way.

Ah, yes, and in order to be able to search for `zinc oxide`, but find the zinc oxide nanoparticles, the row looks like

```
NPO_1542,zinc_oxide_nanoparticle,ZnO_nanoparticle,zinc_oxide,ZnO
```

Ideally the last entries should come from the links to the chemical structure defined by the ontology , i.e. [#49](https://github.com/enanomapper/ontologies/issues/49).

**Comment by vedina** [comment]
This search is already possible via search.data.enanomapper.net (subject to available annotations!)

https://search.data.enanomapper.net/?search=ENM_9000006

https://search.data.enanomapper.net/?search=titanium%20oxide%20nanoparticle
