### ISSUE TITLE
Some ideas for improving findability of information

### ISSUE THREAD

**Issue by fehrhart** [enanomapper/data.enanomapper.net#47]
Some ideas for improving findability of information (from science cafe UM):
- For many links it is not clear where they are leading to. E.g. raw data, more detailed information or directing back to search function.
- The term bundles is misleading, it indicates upload bundles instead of bundle-data source. Maybe call it "external data sources"?
- Give links to raw/orginal data source - e.g. MODENA data links to MODENA project web page instead.
- The link to the API should be more intuitive to find - e.g. give a link to eNM for developers with information about API and other more technical stuff.

**Comment by vedina** [comment]
- please give example(s)
- Menu bundles renamed to "data collection" , see #48
- MODENA data links to the project page as advised by the data owners; there is no public link for the original data source
- The menu is rearranged, API link is under `For developers` entry , see #48

**Comment by fehrhart** [comment]
Point 2 - 3: great, thanks!

Point 1, example for slightly misleading links: 
The reference substance UUID refers correctly to a substance. But the substance UUID refers to the whole study - and the same does substance name. 

![links](https://cloud.githubusercontent.com/assets/11389574/15107069/d1bf0670-15cd-11e6-8cf8-1b7cd40945c4.gif)

**Comment by vedina** [comment]
- This is intentional, and was a requirement in another use case (as the study link includes all relevant info about substance , including the substance info itself)
- The reference substance (originates from the IUCLID data model and [reference substances](http://iuclid.eu/index.php?fuseaction=home.downloadsubstances)) do not contain study information, hence it links to the entry itself (which is a representative chemical structure in most cases).

**Comment by fehrhart** [comment]
Ok.. if there is a reason better leave it this way.
