### ISSUE TITLE
selected labels do not properly show the number of hits

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#82]
When selected, the label is greyed out (which I liked), but when hovering over it, the number of hits for that label falls behind other labels, making the number largely invisible:

![image](https://cloud.githubusercontent.com/assets/26721/19466977/eab8cd58-950e-11e6-9091-0959f658c05a.png)

**Comment by thejonan** [comment]
I guess this issue is not showing up only with selected tags (labels), but in general? This is a problem we know, and the only solution is to extend the gap between labels in general, which in turn will reduce the number of simultaneously visible labels. I'll think what could be  the best possible workaround.
